### ISSUE TITLE
Serviceordre

### ISSUE THREAD

**Issue by ineant** [Gruppe-9-uia/Prosjekt#24]
oppe på serviceordre siden står det:
Microsoft.AspNetCore.Mvc.Rendering.MvcForm {

vet ikke helt hvor dette kommer ifra så vet ikke hvordan jeg fjerner det

**Comment by AndrineCF** [comment]
` @Html.BeginForm("Save", "Serviceordre") {
        @Html.AntiForgeryToken(`

Er ikke lukke ordentlig så kan være derfor
