### ISSUE TITLE
Noe rart med serivceordre etter trykt submit 

### ISSUE THREAD

**Issue by ineant** [Gruppe-9-uia/Prosjekt#40]
Dette kommer opp over formen etter man trykker på send inn knappen. 
antar det kanskje kommer av man ikke har koblet denne opp til databasen enda, eller controller/modell er noe rart med akkurat nå. men vet ikke helt ennå:

Opprett ny serviceordre
- The Customer field is required.
- The SerialNr_str field is required.
- The value 'jsdkhf' is not valid for SerialNr_str.
- The ProductName_str field is required.
- The CustomerProduct field is required.
- The Checklist field is required.
- The LastName_str field is required.
- The State_str field is required.
- The customers field is required.
- The ServiceOrders field is required.
- The ServiceForms field is required.
- The CustomerProducts field is required.
- The ServiceFormsSign field is required.
- The WarrantyType_str field is required.
- The CustomerProduct field is required.
- The ServiceOrderServiceform field is required.
- The CustomerProductModel field is required.

**Comment by AndrineCF** [comment]
Fikset
